version: "3.8"

services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin

        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - postgres
        restart: unless-stopped

    nestjs:
        container_name: nestjs
        ports:
            - "3000:3000"
        build: ./srcs/backend/
        restart: unless-stopped
        volumes:
            - nestjs:/usr/src/app

volumes:
    nestjs:
        driver: local
        driver_opts:
            type: none
            device: ./srcs/backend
            o: bind
    postgres:
        driver: local
        driver_opts:
            type: none
            device: ./srcs/db/postgres
            o: bind
    pgadmin:
        driver: local
        driver_opts:
            type: none
            device: ./srcs/db/pgadmin
            o: bind

networks:
    postgres:
        driver: bridge