version: "3.8"

services:
    # nestjs:
    #     container_name: nestjs
    #     ports:
    #         - "9999:9999"
    #     build: ./srcs/backend/
    #     restart: unless-stopped
    #     volumes:
    #         - nestjs:/usr/src/app
    #         - react:/usr/src/frontend
    #     networks:
    #         - ft_transcendence

    # react:
    #     container_name: react
    #     ports:
    #         - "3000:3000"
    #     build: ./srcs/frontend/
    #     restart: unless-stopped
    #     volumes:
    #         - react:/usr/src/frontend
    #     networks:
    #         - ft_transcendence

    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            POSTGRES_DB: 'ft_transcendence'
            PGDATA: /data/postgres
        # volumes:
            # - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - ft_transcendence
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        # volumes:
        #     - pgadmin:/var/lib/pgadmin

        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - ft_transcendence
        restart: unless-stopped

# volumes:
    # nestjs:
    #     driver: local
    #     driver_opts:
    #         type: none
    #         device: ./srcs/backend
    #         o: bind
    # react:
    #     driver: local
    #     driver_opts:
    #         type: none
    #         device: ./srcs/frontend/ft_transcendence/website
    #         o: bind
    # postgres:
    #     driver: local
    #     driver_opts:
    #         type: none
    #         device: /home/lucille/transcendence/srcs/db/postgres
    #         o: bind
    # pgadmin:
    #     driver: local
    #     driver_opts:
    #         type: none
    #         device: /home/lucille/transcendence/srcs/db/pgadmin
    #         o: bind

networks:
    ft_transcendence:
        driver: bridge