# del sylducam's yml to work on his mac
version: "3.8"

services:
    nestjs:
        container_name: nestjs
        ports:
            - "9999:9999"
        build: ./srcs/backend/
        restart: unless-stopped
        volumes:
            - ./srcs/backend/src:/usr/src/app/src
            - ./srcs/backend/test:/usr/src/app/test
        networks:
            - ft_transcendence

    react:
        container_name: react
        ports:
            - "3000:3000"
        build: ./srcs/frontend
        restart: unless-stopped
        volumes:
            - ./srcs/frontend/src:/usr/src/app/src
            - ./srcs/frontend/public:/usr/src/app/public
        networks:
            - ft_transcendence

    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            POSTGRES_DB: 'ft_transcendence'
            PGDATA: /data/postgres
        volumes:
            # TODO next line was modified in order for me to be able to work on my mac. Keep the one from Timothee elsewhere
            - ./srcs/db/postgres:/data/postgres
        networks:
            - ft_transcendence
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            # TODO next line was modified in order for me to be able to work on my mac. Keep the one from Timothee elsewhere
            - ./srcs/db/pgadmin:/var/lib/pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - ft_transcendence
        restart: unless-stopped

networks:
    ft_transcendence:
        driver: bridge
